name: CI

on: push

jobs:
  build:
    name: "✏️ Changelog generation"
    runs-on: ubuntu-18.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "✏️ Generate full changelog"
        id: generate-full-changelog
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          headerLabel: "# Changelog"
          enhancementLabel: '### 🚀 Enhancements'
          bugsLabel: '### 🐛 Bug fixes'
          prLabel: '### 📁 Other pull requests'
          addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
          issues: false
          author: false
          unreleased: true
          compareLink: true
          stripGeneratorNotice: true
          verbose: true
      - name: "🖨️ Print changelog to console"
        run: cat CHANGELOG.md
      - name: "📤 Upload changelog"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Changelog"
          path: CHANGELOG.md